/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SanityPublishPlugin
});
module.exports = __toCommonJS(main_exports);

// SanitySettingTab.ts
var import_obsidian = require("obsidian");
function splitSyncRows(raw) {
  const rows = [];
  for (const line of (raw || "").split(/\r?\n/)) {
    const t = line.trim();
    if (!t) continue;
    const i = t.indexOf(":");
    if (i === -1) rows.push({ sanity: t, fm: "" });
    else
      rows.push({
        sanity: t.slice(0, i).trim(),
        fm: t.slice(i + 1).trim()
      });
  }
  while (rows.length < 10) rows.push({ sanity: "", fm: "" });
  return rows;
}
function joinSyncRows(rows) {
  return rows.filter((r) => r.sanity.trim()).map((r) => r.sanity.trim() + (r.fm.trim() ? ":" + r.fm.trim() : "")).join("\n");
}
var DEFAULT_SETTINGS = {
  apiToken: "",
  projectId: "",
  sanityApiBaseUrl: "",
  dataset: "production",
  sanityTypeName: "post",
  sanityBodyField: "body",
  filenameField: "",
  contentDivider: "",
  pullFolder: "",
  syncFields: "",
  announcementText: "",
  announcementLink: "",
  announcementType: "info"
};
var SanitySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Sanity configuration").setHeading();
    new import_obsidian.Setting(containerEl).setName("Sanity API token").setDesc(
      "Your token must have write-access for the project you wish to publish to."
    ).addText(
      (text) => text.setPlaceholder("Enter Your Token").setValue(this.plugin.settings.apiToken || "").onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Project ID").setDesc("Your Sanity project's ID.").addText(
      (text) => text.setPlaceholder("Enter Your Id").setValue(this.plugin.settings.projectId || "").onChange(async (value) => {
        this.plugin.settings.projectId = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Dataset name").setDesc(
      "The name of the dataset you'd like to publish to (defaults to `production`)."
    ).addText(
      (text) => text.setPlaceholder("Enter Your Dataset's Name").setValue(this.plugin.settings.dataset || "production").onChange(async (value) => {
        this.plugin.settings.dataset = value || "production";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Schema configuration").setHeading();
    new import_obsidian.Setting(containerEl).setName("Type name").setDesc(
      "The name of the document type you want to sync with in Sanity (defaults to 'post')."
    ).addText(
      (text) => text.setPlaceholder("Enter Your Type Name").setValue(this.plugin.settings.sanityTypeName || "post").onChange(async (value) => {
        this.plugin.settings.sanityTypeName = value || "post";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Title field").setDesc(
      "The name of the field you'd like to sync your title with (leave blank if you don't want to sync this field)."
    ).addText(
      (text) => text.setPlaceholder("Enter Your Field Name").setValue(this.plugin.settings.sanityTitleField || "").onChange(async (value) => {
        this.plugin.settings.sanityTitleField = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Body field").setDesc(
      "The name of the field you'd like to sync the body of your document with (defaults to 'body')."
    ).addText(
      (text) => text.setPlaceholder("Enter Your Field Name").setValue(this.plugin.settings.sanityBodyField || "body").onChange(async (value) => {
        this.plugin.settings.sanityBodyField = value || "body";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Filename field").setDesc(
      "The Sanity field used to generate the Obsidian filename (and optionally the URL slug). GROQ paths allowed, e.g. 'slug.current'. Leave blank to use the Title field instead."
    ).addText(
      (text) => text.setPlaceholder("e.g. slug.current").setValue(this.plugin.settings.filenameField || "").onChange(async (value) => {
        this.plugin.settings.filenameField = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Advanced").setHeading();
    new import_obsidian.Setting(containerEl).setName("Content divider").setDesc(
      "An optional dividing string for your content. If this string is in your document, anything below it won't be published."
    ).addText(
      (text) => text.setPlaceholder("Enter your divider").setValue(this.plugin.settings.contentDivider || "").onChange(async (value) => {
        this.plugin.settings.contentDivider = value || "";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Pull folder").setDesc(
      "Folder where posts pulled from Sanity are saved. Leave blank to save at the vault root."
    ).addText(
      (text) => text.setPlaceholder("e.g. Sanity").setValue(this.plugin.settings.pullFolder || "").onChange(async (value) => {
        this.plugin.settings.pullFolder = value || "";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Custom API base URL (optional)").setDesc(
      "Reverse-proxy URL used to reach the Sanity API when `api.sanity.io` is unreachable (e.g. in mainland China). Leave blank to use the default host. Enter e.g. `https://sanity-api.your-domain.com` \u2014 the path after the host is preserved, so query / mutate / upload all go through the proxy."
    ).addText(
      (text) => text.setPlaceholder("https://sanity-api.your-domain.com").setValue(this.plugin.settings.sanityApiBaseUrl || "").onChange(async (value) => {
        this.plugin.settings.sanityApiBaseUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Additional fields to sync").setDesc(
      "Extra Sanity fields to sync into each note's frontmatter (and back on publish). One row per field \u2014 left = Sanity field (GROQ path allowed, e.g. `slug.current`), right = frontmatter key (leave blank to reuse the Sanity field name). Fill as many rows as you need; blank rows are ignored."
    );
    const rows = splitSyncRows(this.plugin.settings.syncFields);
    const box = containerEl.createDiv({ cls: "sanity-sync-box" });
    const persist = async () => {
      this.plugin.settings.syncFields = joinSyncRows(rows);
      await this.plugin.saveSettings();
    };
    for (let i = 0; i < 10; i++) {
      const rowEl = box.createDiv({ cls: "sanity-sync-row" });
      const left = new import_obsidian.TextComponent(rowEl).setPlaceholder("Sanity \u5B57\u6BB5 (\u5982 slug.current)").setValue(rows[i].sanity).onChange(async (v) => {
        rows[i].sanity = v;
        await persist();
      });
      left.inputEl.addClass("sanity-sync-input");
      const right = new import_obsidian.TextComponent(rowEl).setPlaceholder("Frontmatter \u952E (\u53EF\u7559\u7A7A)").setValue(rows[i].fm).onChange(async (v) => {
        rows[i].fm = v;
        await persist();
      });
      right.inputEl.addClass("sanity-sync-input");
    }
    new import_obsidian.Setting(containerEl).setName("Site announcement (optional)").setHeading();
    containerEl.createEl("p", {
      text: "\u586B\u5199\u540E\u6267\u884C\u547D\u4EE4\u300CPublish announcement to Sanity\u300D\uFF0C\u7F51\u7AD9\u516C\u544A\u680F\u5373\u663E\u793A\uFF1B\u4E09\u9879\u5168\u7A7A\u5219\u4E0D\u663E\u793A\u3002",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Announcement text").setDesc("\u516C\u544A\u6B63\u6587\u3002\u7559\u7A7A = \u4E0D\u663E\u793A\u516C\u544A\u3002").addText(
      (text) => text.setPlaceholder("\u5982\uFF1A\u672C\u7AD9\u5DF2\u5347\u7EA7\u4E2A\u6027\u5316\u6837\u5F0F").setValue(this.plugin.settings.announcementText || "").onChange(async (value) => {
        this.plugin.settings.announcementText = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Announcement link").setDesc("\u70B9\u51FB\u516C\u544A\u8DF3\u8F6C\u7684\u94FE\u63A5\uFF08\u53EF\u7559\u7A7A\uFF09\u3002").addText(
      (text) => text.setPlaceholder("/about/").setValue(this.plugin.settings.announcementLink || "").onChange(async (value) => {
        this.plugin.settings.announcementLink = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Announcement type").setDesc("info / success / warn\uFF0C\u5BF9\u5E94\u4E0D\u540C\u5F3A\u8C03\u8272\u3002").addDropdown(
      (dd) => dd.addOption("info", "info").addOption("success", "success").addOption("warn", "warn").setValue(this.plugin.settings.announcementType || "info").onChange(async (value) => {
        this.plugin.settings.announcementType = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// main.ts
var import_obsidian2 = require("obsidian");
var httpRegex = /^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$/;
var API_VERSION = "2023-05-03";
var QUERY_API_VERSION = "v2021-06-07";
function apiBaseFor(settings) {
  var _a;
  const custom = (_a = settings.sanityApiBaseUrl) == null ? void 0 : _a.trim().replace(/\/+$/, "");
  return custom || `https://${settings.projectId}.api.sanity.io`;
}
function sanityErrorText(res) {
  var _a, _b, _c, _d, _e;
  const err = (_a = res.json) == null ? void 0 : _a.error;
  const desc = (typeof err === "string" ? err : err == null ? void 0 : err.description) || ((_b = res.json) == null ? void 0 : _b.message) || res.text;
  const itemType = (_e = (_d = (_c = err == null ? void 0 : err.items) == null ? void 0 : _c[0]) == null ? void 0 : _d.error) == null ? void 0 : _e.type;
  const detail = desc ? String(desc).slice(0, 400) : "(\u65E0\u54CD\u5E94\u4F53)";
  return itemType ? `${detail} [${itemType}]` : detail;
}
async function sanityMutate(mutations, settings) {
  const url = `${apiBaseFor(settings)}/v${API_VERSION}/data/mutate/${settings.dataset}?returnIds=true&returnDocuments=true&visibility=sync`;
  const res = await (0, import_obsidian2.requestUrl)({
    url,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${settings.apiToken}`
    },
    body: JSON.stringify({ mutations }),
    throw: false
  });
  if (res.status >= 400) {
    const reason = sanityErrorText(res);
    console.error("Sanity mutate failed", res.status, res.text);
    throw new Error(`Sanity mutate ${res.status}: ${reason}`);
  }
  return res.json;
}
function parseSyncFields(raw) {
  const out = [];
  if (!raw) return out;
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const idx = trimmed.indexOf(":");
    let expr;
    let key;
    if (idx === -1) {
      expr = trimmed;
      key = trimmed.replace(/[^A-Za-z0-9_]/g, "_");
    } else {
      expr = trimmed.slice(0, idx).trim();
      key = trimmed.slice(idx + 1).trim().replace(/[^A-Za-z0-9_]/g, "_");
    }
    expr = cleanGroqExpr(expr);
    if (!expr || !key) continue;
    out.push({ expr, key });
  }
  return out;
}
function cleanGroqExpr(expr) {
  return expr.replace(/[^A-Za-z0-9_.[\]]/g, "");
}
function setDeepPath(obj, path, value) {
  const keys = path.split(".");
  let cur = obj;
  for (let i = 0; i < keys.length - 1; i++) {
    const k = keys[i];
    if (!cur[k] || typeof cur[k] !== "object") cur[k] = {};
    cur = cur[k];
  }
  cur[keys[keys.length - 1]] = value;
}
function sanityAssetUrlFromRef(ref, projectId, dataset) {
  const m = ref.match(/^image-(.*)-(\d+x\d+)-(\w+)$/);
  if (!m) return null;
  const [, assetId, dims, ext] = m;
  return `https://cdn.sanity.io/images/${projectId}/${dataset}/${assetId}-${dims}.${ext}`;
}
function sanityRefFromAssetUrl(url, projectId, dataset) {
  const m = url.match(
    /^https:\/\/cdn\.sanity\.io\/images\/(.+?)\/(.+?)\/(.+)-(\d+x\d+)\.(\w+)$/
  );
  if (!m) return null;
  const [, p, d, assetId, dims, ext] = m;
  if (p !== projectId || d !== dataset) return null;
  return `image-${assetId}-${dims}-${ext}`;
}
function guessMime(ext) {
  const map = {
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    gif: "image/gif",
    webp: "image/webp",
    svg: "image/svg+xml",
    bmp: "image/bmp",
    ico: "image/x-icon",
    pdf: "application/pdf",
    mp4: "video/mp4",
    webm: "video/webm",
    mp3: "audio/mpeg",
    wav: "audio/wav",
    ogg: "audio/ogg",
    zip: "application/zip",
    json: "application/json",
    txt: "text/plain",
    md: "text/markdown",
    csv: "text/csv"
  };
  return ext && map[ext.toLowerCase()] || "application/octet-stream";
}
function parseFrontmatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { data: {}, content: raw };
  let data = {};
  try {
    data = (0, import_obsidian2.parseYaml)(m[1]) || {};
  } catch (e) {
    data = {};
  }
  return { data, content: m[2] };
}
var ProgressModal = class extends import_obsidian2.Modal {
  constructor() {
    super(...arguments);
    this.total = 0;
    this.failures = [];
  }
  openProgress(total, title) {
    this.total = total;
    this.failures = [];
    this.titleEl.setText(title);
    this.contentEl.empty();
    this.bar = this.contentEl.createEl("progress", {
      cls: "sanity-progress"
    });
    this.bar.max = Math.max(total, 1);
    this.bar.value = 0;
    this.statusEl = this.contentEl.createEl("p", {
      cls: "sanity-progress-status",
      text: "\u51C6\u5907\u4E2D\u2026"
    });
    this.open();
  }
  /** current 从 1 开始计；label 为当前项的可读名称（文件名 / 文章标题）。 */
  update(current, label) {
    this.bar.value = current;
    const txt = `${current} / ${this.total}`;
    this.statusEl.setText(label ? `${txt} \u2014 ${label}` : txt);
  }
  addFailure(name) {
    this.failures.push(name);
  }
  finish(message, autoCloseMs = 1500) {
    this.bar.value = this.total;
    this.statusEl.setText(message);
    if (this.failures.length) {
      const failEl = this.contentEl.createEl("p", {
        cls: "sanity-progress-fail",
        text: `\u5931\u8D25 ${this.failures.length} \u9879\uFF1A${this.failures.join("\u3001")}`
      });
    }
    if (autoCloseMs > 0) window.setTimeout(() => this.close(), autoCloseMs);
  }
};
var SanityPublishPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (!file || !(file.extension === "md")) {
          this.removeStatusBarButton();
          return;
        }
        this.addStatusBarButton(file);
      })
    );
    this.addCommand({
      id: "publish",
      name: "Publish to Sanity",
      callback: () => {
        const activeFile = this.app.workspace.getActiveFile();
        if (!activeFile) {
          new import_obsidian2.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6\uFF0C\u518D\u6267\u884C\u53D1\u5E03\u3002");
          return;
        }
        this.publishToSanity(activeFile).catch((e) => {
          console.error("Publish crashed:", e);
          new import_obsidian2.Notice("Publish \u51FA\u9519\uFF1A" + ((e == null ? void 0 : e.message) || String(e)), 1e4);
        });
      }
    });
    this.addCommand({
      id: "pull",
      name: "Pull from Sanity (sync all posts)",
      callback: () => {
        this.pullFromSanity().catch((e) => {
          console.error("Pull crashed:", e);
          new import_obsidian2.Notice("Pull \u51FA\u9519\uFF1A" + ((e == null ? void 0 : e.message) || String(e)), 1e4);
        });
      }
    });
    this.addCommand({
      id: "publish-announcement",
      name: "Publish announcement to Sanity",
      callback: () => {
        this.publishAnnouncementToSanity().catch((e) => {
          console.error("Publish announcement crashed:", e);
          new import_obsidian2.Notice("\u53D1\u5E03\u516C\u544A\u51FA\u9519\uFF1A" + ((e == null ? void 0 : e.message) || String(e)), 1e4);
        });
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, info) => {
        const lineNumber = editor.getCursor().line;
        const line = editor.getLine(lineNumber);
        const filePath = this.getFilePathFromLine(line);
        if (!filePath) return;
        const fileMetaData = this.app.metadataCache.getFirstLinkpathDest(filePath, "");
        if (!fileMetaData) return;
        menu.addItem((item) => {
          item.setTitle("Upload to Sanity").setIcon("file-up").onClick(() => {
            const uploadText = `![uploading file...](${filePath})`;
            editor.setLine(lineNumber, uploadText);
            this.uploadFileToSanity(fileMetaData).then((value) => {
              const assetText = `![${value.originalFilename}](${value.url})`;
              editor.setLine(lineNumber, assetText);
            }).catch((r) => {
              console.error("Upload to Sanity failed", r);
              const errorText = `![Couldn't upload file](${filePath})`;
              editor.setLine(lineNumber, errorText);
            });
          });
        });
      })
    );
    this.addSettingTab(new SanitySettingTab(this.app, this));
  }
  onunload() {
  }
  addStatusBarButton(file) {
    if (this.statusBarButton) return;
    const statusButton = this.addStatusBarItem();
    const iconSpan = statusButton.createEl("span");
    (0, import_obsidian2.setIcon)(iconSpan, "file-up");
    statusButton.createEl("span", {
      text: "Publish"
    });
    statusButton.addClass("mod-clickable");
    statusButton.setAttr("aria-label", "Publish to Sanity");
    statusButton.setAttr("data-tooltip-position", "top");
    statusButton.addEventListener("click", () => {
      this.publishToSanity(file).catch((e) => {
        console.error("Publish crashed:", e);
        new import_obsidian2.Notice("Publish \u51FA\u9519\uFF1A" + ((e == null ? void 0 : e.message) || String(e)), 1e4);
      });
    });
    this.statusBarButton = statusButton;
  }
  removeStatusBarButton() {
    if (this.statusBarButton) this.statusBarButton.remove();
    this.statusBarButton = void 0;
  }
  /**
   * 取正对着目标文件的编辑器实例。
   *
   * 注意：`getActiveFile()` 与 `getActiveViewOfType(MarkdownView)` 并不等价——
   * 从命令面板触发时焦点已转移到 suggestion 弹窗，文件在阅读视图/其它 leaf 打开时
   * 也拿不到 MarkdownView。所以这里允许返回 null，由调用方退回 vault 读写。
   */
  getEditorForFile(file) {
    var _a, _b;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (!view) return null;
    if (((_a = view.file) == null ? void 0 : _a.path) !== file.path) return null;
    return (_b = view.editor) != null ? _b : null;
  }
  /**
   * 读取目标文件的 frontmatter + 正文。
   * 优先取编辑器内容（含尚未保存的改动），取不到就读盘，
   * 因此不再依赖「必须有活动 MarkdownView」。
   */
  async getFileData(file) {
    const editor = this.getEditorForFile(file);
    const raw = editor ? editor.getValue() : await this.app.vault.read(file);
    return parseFrontmatter(raw);
  }
  async uploadAllImages(file) {
    const editor = this.getEditorForFile(file);
    const content = editor ? editor.getValue() : await this.app.vault.read(file);
    const lines = content.split("\n");
    const targets = lines.map((line, lineNumber) => ({
      lineNumber,
      filePath: this.getFilePathFromLine(line)
    })).filter(
      (t) => Boolean(t.filePath)
    );
    if (targets.length === 0) return;
    const modal = new ProgressModal(this.app);
    modal.openProgress(targets.length, "\u4E0A\u4F20\u56FE\u7247\u5230 Sanity");
    let done = 0;
    let okCount = 0;
    await Promise.all(
      targets.map(async ({ lineNumber, filePath }) => {
        const fileMetaData = this.app.metadataCache.getFirstLinkpathDest(
          filePath,
          file.path
        );
        if (!fileMetaData) {
          done++;
          modal.update(done);
          return;
        }
        if (editor) {
          editor.setLine(
            lineNumber,
            `![uploading file...](${filePath})`
          );
        }
        try {
          const value = await this.uploadFileToSanity(fileMetaData);
          lines[lineNumber] = `![${value.originalFilename}](${value.url})`;
          okCount++;
        } catch (e) {
          console.error("Upload to Sanity failed", e);
          lines[lineNumber] = `![Couldn't upload file](${filePath})`;
          modal.addFailure(fileMetaData.name);
        }
        if (editor) editor.setLine(lineNumber, lines[lineNumber]);
        done++;
        modal.update(done, fileMetaData.name);
      })
    );
    if (!editor) await this.app.vault.modify(file, lines.join("\n"));
    const failed = targets.length - okCount;
    modal.finish(
      `\u4E0A\u4F20\u5B8C\u6210\uFF1A${okCount}/${targets.length} \u6210\u529F` + (failed ? `\uFF0C${failed} \u5931\u8D25` : "")
    );
  }
  async publishToSanity(activeFile) {
    await this.uploadAllImages(activeFile);
    const { content, data } = await this.getFileData(activeFile);
    new import_obsidian2.Notice("Publishing content to Sanity...");
    const titleField = this.settings.sanityTitleField;
    const bodyField = this.settings.sanityBodyField;
    const fmTitle = titleField ? data == null ? void 0 : data[titleField] : void 0;
    const title = typeof fmTitle === "string" && fmTitle ? fmTitle : activeFile.basename;
    const extraAttrs = {};
    const extraFields = parseSyncFields(this.settings.syncFields);
    const syncedKeys = /* @__PURE__ */ new Set();
    for (const f of extraFields) {
      syncedKeys.add(f.key);
      const raw = data == null ? void 0 : data[f.key];
      if (raw === void 0 || raw === null) continue;
      if (f.key === titleField || f.key === bodyField) continue;
      const value = await this.coerceSyncValue(raw, activeFile, f.key);
      setDeepPath(extraAttrs, f.expr, value);
    }
    const skip = new Set(syncedKeys);
    if (titleField) skip.add(titleField);
    if (bodyField) skip.add(bodyField);
    skip.add("sanity_id");
    skip.add("sanity_draft");
    for (const [k, v] of Object.entries(data || {})) {
      if (skip.has(k)) continue;
      if (v === void 0 || v === null) continue;
      const value = await this.coerceSyncValue(v, activeFile, k);
      setDeepPath(extraAttrs, k, value);
    }
    const r = await this.createorUpdateDocument({
      content,
      title,
      sanityId: data == null ? void 0 : data.sanity_id,
      extra: extraAttrs
    });
    if (r == null ? void 0 : r._id) {
      await this.updateFrontmatter(
        { sanity_id: r._id, sanity_draft: false },
        activeFile
      );
      new import_obsidian2.Notice("Successfully published content to Sanity!");
    }
  }
  /** 把 frontmatter 里的封面值解析成可写入 Sanity 的值：
   *  - 已是 image object -> 原样返回
   *  - cdn.sanity.io URL -> 还原 asset ref -> image object
   *  - 其它 http(s) 外链 -> 原样字符串返回（保守，不假设 schema）
   *  - 本地附件路径（可带 [[ ]] 包裹）-> 上传到 Sanity assets -> image object
   * 本地路径在库里找不到或上传失败时返回 undefined（不写封面，避免写入无效路径）。 */
  async resolveCoverValue(raw, file, coverField) {
    if (raw && typeof raw === "object" && raw._type === "image" && raw.asset && typeof raw.asset._ref === "string") {
      return raw;
    }
    if (typeof raw !== "string") return raw;
    const { projectId, dataset } = this.settings;
    if (raw.startsWith("https://cdn.sanity.io/images/")) {
      const ref = sanityRefFromAssetUrl(raw, projectId || "", dataset);
      if (ref) {
        return { _type: "image", asset: { _type: "reference", _ref: ref } };
      }
      return raw;
    }
    if (/^https?:\/\//i.test(raw)) return raw;
    const linkpath = raw.replace(/^\[\[|\]\]$/g, "").trim();
    const meta = this.app.metadataCache.getFirstLinkpathDest(linkpath, file.path);
    if (!meta) {
      new import_obsidian2.Notice(`\u5C01\u9762\u300C${raw}\u300D\u5728\u5E93\u4E2D\u672A\u627E\u5230\uFF0C\u672A\u5199\u5165\u5C01\u9762\u5B57\u6BB5\u3002`, 8e3);
      return void 0;
    }
    try {
      const up = await this.uploadFileToSanity(meta);
      const ref = sanityRefFromAssetUrl(up.url, projectId || "", dataset);
      if (ref) {
        return { _type: "image", asset: { _type: "reference", _ref: ref } };
      }
      return raw;
    } catch (e) {
      new import_obsidian2.Notice("\u5C01\u9762\u4E0A\u4F20\u5931\u8D25\uFF1A" + ((e == null ? void 0 : e.message) || String(e)), 8e3);
      return void 0;
    }
  }
  /** 判断 frontmatter 值是否像本地图片（用于发布时把该字段自动上传成 image asset）。
   *  仅认本地路径 / [[ ]] wikilink（带图片扩展名）；外链（含 cdn.sanity.io）不在此判断，
   *  避免误把普通字符串字段（title/slug 等）当封面处理。 */
  looksLikeImage(raw) {
    if (!raw || typeof raw !== "string") return false;
    const s = raw.replace(/^\[\[|\]\]$/g, "").trim();
    if (/^https?:\/\//i.test(s)) return false;
    return /\.(png|jpe?g|webp|gif|avif|bmp|svg)$/i.test(s);
  }
  /** 判断 Sanity 返回值是否为 image object（{_type:"image", asset:{_ref}}）。 */
  isImageObject(v) {
    return !!(v && v._type === "image" && v.asset && typeof v.asset._ref === "string");
  }
  /** 把 frontmatter 值转换为写入 Sanity 的值：
   *  - 本地图片（含 [[ ]] 包裹）/cdn.sanity.io URL -> image object（asset ref）
   *  - 其它值原样返回。
   * 供 syncFields 显式映射与「兜底自动同步」两处复用，避免重复图片转换逻辑。 */
  async coerceSyncValue(raw, file, key) {
    if (this.looksLikeImage(raw)) {
      const coverVal = await this.resolveCoverValue(raw, file, key);
      return coverVal !== void 0 ? coverVal : raw;
    }
    if (typeof raw === "string" && raw.startsWith("https://cdn.sanity.io/images/")) {
      const ref = sanityRefFromAssetUrl(
        raw,
        this.settings.projectId || "",
        this.settings.dataset
      );
      if (ref) {
        return {
          _type: "image",
          asset: { _type: "reference", _ref: ref }
        };
      }
    }
    return raw;
  }
  async publishAnnouncementToSanity() {
    const { announcementText, announcementLink, announcementType } = this.settings;
    if (!announcementText || !announcementText.trim()) {
      new import_obsidian2.Notice("\u516C\u544A\u6587\u672C\u4E3A\u7A7A\uFF0C\u672A\u53D1\u5E03\uFF08\u7559\u7A7A\u5219\u4E0D\u663E\u793A\uFF09\u3002");
      return;
    }
    const doc = {
      _id: "siteSettings",
      _type: "siteSettings",
      announcementText: announcementText.trim(),
      announcementLink: (announcementLink || "").trim(),
      announcementType: (announcementType || "info").trim()
    };
    try {
      await sanityMutate([{ createOrReplace: doc }], this.settings);
      new import_obsidian2.Notice("\u516C\u544A\u5DF2\u53D1\u5E03\u5230 Sanity\uFF0C\u7F51\u7AD9\u7A0D\u540E\u81EA\u52A8\u66F4\u65B0\u3002");
    } catch (e) {
      console.error("Publish announcement failed:", e);
      new import_obsidian2.Notice("\u53D1\u5E03\u516C\u544A\u5931\u8D25\uFF1A" + ((e == null ? void 0 : e.message) || String(e)), 1e4);
    }
  }
  async pullFromSanity() {
    var _a, _b, _c;
    const { projectId, dataset, apiToken } = this.settings;
    if (!projectId || !apiToken) {
      new import_obsidian2.Notice(
        "\u8BF7\u5148\u5728\u63D2\u4EF6\u8BBE\u7F6E\u4E2D\u586B\u5199 Sanity Project ID \u548C API Token\uFF0C\u518D\u6267\u884C\u62C9\u53D6\u3002"
      );
      return;
    }
    new import_obsidian2.Notice("Pulling all posts from Sanity...");
    const type = this.settings.sanityTypeName || "post";
    const titleField = this.settings.sanityTitleField;
    const bodyField = this.settings.sanityBodyField || "body";
    const filenameField = this.settings.filenameField;
    const safeType = String(type).replace(/[^a-zA-Z0-9_]/g, "");
    const safeTitle = titleField ? cleanGroqExpr(titleField) : "";
    const safeBody = bodyField ? cleanGroqExpr(bodyField) : "";
    const safeFilename = filenameField ? cleanGroqExpr(filenameField) : "";
    const extraFields = parseSyncFields(this.settings.syncFields);
    const parts = [`_id`, `"isDraft": _id in path("drafts.**")`];
    if (safeTitle) parts.push(`"_syncTitle": ${safeTitle}`);
    if (safeBody) parts.push(`"_syncBody": ${safeBody}`);
    if (safeFilename) {
      parts.push(`"_syncFilename": ${safeFilename}`);
    } else {
      parts.push(`"_syncFilename": slug.current`);
    }
    for (const f of extraFields) {
      parts.push(`"${f.key}": ${f.expr}`);
    }
    const query = `*[_type == "${safeType}"]{ ${parts.join(", ")} }`;
    let docs = [];
    try {
      const url = `${apiBaseFor(this.settings)}/${QUERY_API_VERSION}/data/query/${dataset}?query=${encodeURIComponent(query)}&perspective=raw`;
      const res = await (0, import_obsidian2.requestUrl)({
        url,
        method: "GET",
        headers: { Authorization: `Bearer ${apiToken}` }
      });
      docs = ((_a = res.json) == null ? void 0 : _a.result) || [];
    } catch (e) {
      const status = e == null ? void 0 : e.status;
      const detail = (e == null ? void 0 : e.message) || ((_b = e == null ? void 0 : e.response) == null ? void 0 : _b.text) || (e == null ? void 0 : e.text) || String(e);
      console.error("Sanity pull failed:", status, detail, "project=", projectId);
      let msg;
      if (!status) {
        msg = `\u62C9\u53D6\u5931\u8D25\uFF1A\u65E0\u6CD5\u8FDE\u63A5\u5230 Sanity\uFF08\u7F51\u7EDC\u9519\u8BEF\uFF09\u3002
\u8BF7\u68C0\u67E5\uFF1A\u2460\u624B\u673A\u7F51\u7EDC\u80FD\u5426\u8BBF\u95EE ${apiBaseFor(this.settings)}\uFF1B\u2461\u662F\u5426\u9700\u8981 VPN/\u4EE3\u7406\uFF1B\u2462\u63D2\u4EF6\u8BBE\u7F6E\u91CC\u7684 Project ID / Token / \u81EA\u5B9A\u4E49 API \u57DF\u540D \u662F\u5426\u5DF2\u586B\u5199\u3002`;
      } else {
        msg = `\u62C9\u53D6\u5931\u8D25\uFF08HTTP ${status}\uFF09\uFF1A${detail}`;
      }
      new import_obsidian2.Notice(msg, 12e3);
      return;
    }
    if (!docs.length) {
      new import_obsidian2.Notice("No documents found in Sanity.");
      return;
    }
    const modal = new ProgressModal(this.app);
    modal.openProgress(docs.length, "\u4ECE Sanity \u62C9\u53D6\u6587\u7AE0");
    const existingById = /* @__PURE__ */ new Map();
    for (const f of this.app.vault.getMarkdownFiles()) {
      const fm = (_c = this.app.metadataCache.getFileCache(f)) == null ? void 0 : _c.frontmatter;
      if (fm && fm.sanity_id) existingById.set(fm.sanity_id, f);
    }
    const folderPrefix = this.settings.pullFolder ? this.settings.pullFolder.replace(/\/+$/, "") + "/" : "";
    let created = 0;
    let updated = 0;
    let i = 0;
    for (const doc of docs) {
      const isDraft = !!doc.isDraft;
      let baseName = this.sanitizeFilename(
        filenameField ? doc._syncFilename || "untitled" : doc._syncTitle || doc._syncFilename || doc._id || "untitled"
      );
      if (isDraft) baseName = baseName + "-draft";
      const frontmatter = {
        sanity_id: doc._id,
        sanity_draft: isDraft
      };
      if (safeTitle && doc._syncTitle !== void 0 && doc._syncTitle !== null) {
        frontmatter[safeTitle] = doc._syncTitle;
      }
      for (const f of extraFields) {
        let v = doc[f.key];
        if (v === void 0 || v === null) continue;
        if (this.isImageObject(v)) {
          const url = sanityAssetUrlFromRef(
            v.asset._ref,
            projectId,
            dataset
          );
          if (url) v = url;
        }
        frontmatter[f.key] = v;
      }
      const body = doc._syncBody || "";
      const label = String(doc._syncTitle || doc._syncFilename || doc._id || "untitled") + (isDraft ? " (\u8349\u7A3F)" : "");
      const existing = existingById.get(doc._id);
      if (existing) {
        const raw = await this.app.vault.read(existing);
        const { data } = parseFrontmatter(raw);
        const mergedFm = { ...data, ...frontmatter };
        await this.app.vault.modify(
          existing,
          `---
${(0, import_obsidian2.stringifyYaml)(mergedFm).trimEnd()}
---

${body}`
        );
        updated++;
        i++;
        modal.update(i, label);
        continue;
      }
      let finalPath = folderPrefix + baseName + ".md";
      let n = 1;
      while (await this.app.vault.adapter.exists(finalPath)) {
        finalPath = folderPrefix + baseName + "-" + n + ".md";
        n++;
      }
      await this.app.vault.create(
        finalPath,
        `---
${(0, import_obsidian2.stringifyYaml)(frontmatter).trimEnd()}
---

${body}`
      );
      created++;
      i++;
      modal.update(i, label);
    }
    modal.finish(
      `\u62C9\u53D6\u5B8C\u6210\uFF1A${created} \u65B0\u5EFA\uFF0C${updated} \u66F4\u65B0\uFF08\u5171 ${docs.length} \u7BC7\uFF09`
    );
  }
  sanitizeFilename(name) {
    const cleaned = name.replace(/[\\/:*?"<>|#]/g, "-").replace(/^\.+/, "").trim();
    return cleaned.slice(0, 80) || "untitled";
  }
  async uploadFileToSanity(file) {
    var _a;
    const arrayBuffer = await this.app.vault.readBinary(file);
    const fileType = guessMime(file.extension);
    const isImage = fileType == null ? void 0 : fileType.includes("image");
    const fileName = file.path.split("/").pop() || "file";
    const url = `${apiBaseFor(this.settings)}/v${API_VERSION}/assets/${isImage ? "images" : "files"}/${this.settings.dataset}?filename=${encodeURIComponent(fileName)}`;
    const res = await (0, import_obsidian2.requestUrl)({
      url,
      method: "POST",
      headers: {
        "Content-Type": fileType || "application/octet-stream",
        Authorization: `Bearer ${this.settings.apiToken}`
      },
      body: arrayBuffer,
      throw: false
    });
    if (res.status >= 400) {
      const reason = sanityErrorText(res);
      console.error("Sanity asset upload failed", res.status, res.text);
      throw new Error(`\u4E0A\u4F20\u300C${fileName}\u300D\u5931\u8D25\uFF08HTTP ${res.status}\uFF09\uFF1A${reason}`);
    }
    const doc = ((_a = res.json) == null ? void 0 : _a.document) || res.json;
    return { originalFilename: doc.originalFilename, url: doc.url };
  }
  async createorUpdateDocument({
    title,
    content,
    sanityId,
    extra
  }) {
    const _type = this.settings.sanityTypeName;
    const titleField = this.settings.sanityTitleField;
    const bodyField = this.settings.sanityBodyField;
    if (this.settings.contentDivider) {
      content = content.split(this.settings.contentDivider)[0];
    }
    let attributes = { [bodyField]: content };
    if (titleField) attributes[titleField] = title;
    if (extra) Object.assign(attributes, extra);
    let targetId = sanityId || "";
    let draftToDelete = null;
    if (targetId.startsWith("drafts.")) {
      draftToDelete = targetId;
      targetId = targetId.slice("drafts.".length);
    }
    let mutations;
    if (!targetId) {
      targetId = "post-" + Math.random().toString(36).slice(2, 11);
      mutations = [{ create: { _type, _id: targetId, ...attributes } }];
    } else {
      mutations = [
        { createIfNotExists: { _id: targetId, _type } },
        { patch: { id: targetId, set: attributes } }
      ];
    }
    const res = await sanityMutate(mutations, this.settings);
    const results = res == null ? void 0 : res.results;
    const last = Array.isArray(results) ? results[results.length - 1] : void 0;
    const doc = (last == null ? void 0 : last.document) || ((last == null ? void 0 : last.id) ? { _id: last.id } : void 0);
    if (draftToDelete) {
      await sanityMutate([{ delete: { id: draftToDelete } }], this.settings);
    }
    return (doc == null ? void 0 : doc._id) ? doc : { _id: targetId };
  }
  getFilePathFromLine(line) {
    var _a;
    const matches = line.match(/!\[\[(.*?)\]\]|!\[.*?\]\((.*?)\)/);
    if (!matches) return;
    if ((_a = matches == null ? void 0 : matches[2]) == null ? void 0 : _a.match(httpRegex)) return;
    const filePath = (matches == null ? void 0 : matches[1]) || (matches == null ? void 0 : matches[2]);
    return filePath;
  }
  async updateFrontmatter(updatedProperties, file) {
    const currentFile = file != null ? file : this.app.workspace.getActiveFile();
    if (!currentFile) {
      console.error("No active file found.");
      return;
    }
    const { content, data } = await this.getFileData(currentFile);
    const updatedFrontmatter = `---
${(0, import_obsidian2.stringifyYaml)({ ...data, ...updatedProperties }).trimEnd()}
---
`;
    const updatedContent = updatedFrontmatter + content;
    await this.app.vault.modify(currentFile, updatedContent);
  }
  async sleep(delay) {
    return new Promise((resolve) => window.setTimeout(resolve, delay));
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
